In [ ]:
#when 1000 datapoint and 900 say yes 100 say no. this create a imbalance between the datapoints which will lead to biased answer by the ML model.

In [1]:
# solution are only two
# upsampling
# downsampling

In [6]:
#creating and imbalance dataset.
# In imbalance dataset it is formed when the data got divided into 2 classes for example votes by people as well as if the votes are imbalanced like B900 100A.  
import pandas as pd
import numpy as np

sample_size=1000 # for example total people that will vote
class_0_ratio=0.9 # there is a class voting A i.e with a ratio of 0.9.

total_class_0_supporters = int(sample_size * class_0_ratio) 
total_class_1_supporters = sample_size - total_class_0_supporters

In [7]:
# creating a dataframe where i show the two classes 
# loc = mean (center) → where the values are centered.
# scale = standard deviation (spread) → how spread out the values are.
#normal is the data will be normally distributed

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=total_class_0_supporters),      #size is total datapoints
    'feature_2': np.random.normal(loc=0, scale=1, size=total_class_0_supporters),
    'target': [0] * total_class_0_supporters                                  # target is used to tell the row belongs to which class by 0 or 1.
})

#The model uses the feature values to decide whether a row belongs to class 0 or class 1 (target).

#In your class_0 DataFrame, every row has:
#target = 0
#So all those rows belong to class 0.
#Same idea for class_1 DataFrame:
#every row has target = 1
#Later you combine them so the model learns both classes together.

#We use two or more features for each class 0 & 1 because each sample can have multiple pieces of information that help predict the target. 
# Two features are just a simple example. for example people giving vote can have feature age and income. feature can be 10 or 100 for a class.

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=total_class_1_supporters),      #size is total datapoints
    'feature_2': np.random.normal(loc=2, scale=1, size=total_class_1_supporters),
    'target': [1] * total_class_1_supporters ,                                  # target is used to tell the row belongs to which class by 0 or 1.
})

#Class 0 values are centered around 0(loc)(mean).
#Class 1 values are centered around 2(loc).
#This makes the two classes easier to distinguish.
#If both classes had loc=0, their values would overlap heavily, and a machine learning model would struggle to tell them apart.
#We use loc=2 for Class 1 to make it different from Class 0 (loc=0), so the model can learn to separate the two classes using target 0 or 1 label.

In [ ]:
# now we combine both classes
pd.concat([class_0,class_1])

    feature_1  feature_2  target
0   -0.213945  -0.809918       0
1   -0.130805   0.920071       0
2    1.305468   0.354691       0
3   -1.010494  -0.160387       0
4   -1.205031   0.014486       0
..        ...        ...     ...
95   1.680708   1.191302       1
96   0.847972   1.052598       1
97   2.554779   1.347625       1
98   1.771806   2.073206       1
99   0.436791   2.624702       1

[1000 rows x 3 columns]

In [11]:
# but we are getting extra index in the dataframe
#so we remove it
df=pd.concat([class_0,class_1]).reset_index(drop=True)
df

     feature_1  feature_2  target
0    -0.213945  -0.809918       0
1    -0.130805   0.920071       0
2     1.305468   0.354691       0
3    -1.010494  -0.160387       0
4    -1.205031   0.014486       0
..         ...        ...     ...
995   1.680708   1.191302       1
996   0.847972   1.052598       1
997   2.554779   1.347625       1
998   1.771806   2.073206       1
999   0.436791   2.624702       1

[1000 rows x 3 columns]

In [12]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [13]:
#upsampling where the minority class id resampled upto majority class to remove imbalancing
df_minority=df[df["target"]==1]
df_majority=df[df["target"]==0] # 900

In [16]:
from sklearn.utils import resample

df_minority_upsampled=resample(df_minority, replace=True, n_samples=len(df_majority), random_state=42) #(upsampling data, , upto majority)

#So the same row can be picked again and again.
#In your case (upsampling):
#minority data is small
#you repeat it to match majority size
#so rows are duplicated randomly
#This will always pick the same 100 rows (same duplicates in same order).
#Without random_state:
#each run picks different rows randomly

In [20]:
df_minority_upsampled.shape

(900, 3)

In [21]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   3.614742   2.099997       1
992   2.446063   3.573639       1
914  -0.541178   2.491272       1
971   2.733696   3.106383       1
960   1.563861   0.633336       1

In [26]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [27]:
df_upsampled["target"].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [30]:
#downsample
df_majority_downsampled=resample(df_majority, replace=False, n_samples=len(df_minority), random_state=42)

In [33]:
down_sampled=pd.concat([df_minority,df_majority_downsampled])

In [ ]:
down_sampled["target"].value_counts() # downsampling is bad as we losing datapoints

target
1    100
0    100
Name: count, dtype: int64