# Module: Pandas Assignments
## Lesson: Pandas
### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.
2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.
2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.
2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.
2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.
2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.
2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.
2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.
2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.
2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

In [23]:
import pandas as pd
import numpy as np

df=pd.DataFrame(np.random.randint(1,50,size=(6,4)),columns=['A','B','C','D'])

In [27]:
df.set_index('A',inplace=True)

In [28]:
df

     B   C   D
A
24   1  38  44
32  35  14  19
35  31  41  41
48  28   3   9
8   36  47  25
32  28  37  30

In [48]:
import pandas as pd
import numpy as np
data=pd.DataFrame(np.random.randint(1,20,size=(3,3)),columns=['A','B','C'])
data.set_index(np.array(['X','Y','Z']),inplace=True) # inorder to set rows labels you need to make an np.array and set the row labels there. or use existing column values as row labels.

In [49]:
data

    A   B  C
X  12  10  7
Y  13  19  8
Z  13  10  7

In [ ]:
ele=data.at['Y','B'] # use at for specific element. # or use iloc for indexing accessing like 0,0 position element
print(data.iloc[1,1]) # easy method.
print(ele)

19
19

In [15]:
data=pd.DataFrame(np.random.randint(1,20,size=(5,3)),columns=['A','B','C'])
data

    A   B   C
0   2  17   8
1  19  15  17
2   2   9   5
3  13   2  13
4  10   5  19

In [51]:
data['product_A_B']=data['A']*data['B']
#or 
#data['product_A_B'] = data.apply(lambda x: x['A'] * x['B'], axis=1) we can't use any() function as it is used for logical checks in iterators. not for mathamatical problems

In [18]:
data

    A   B   C  product_A_B
0   2  17   8           34
1  19  15  17          285
2   2   9   5           18
3  13   2  13           26
4  10   5  19           50

In [19]:
data=pd.DataFrame(np.random.randint(1,20,size=(4,3)),columns=['A','B','C'])

In [20]:
data

    A   B   C
0  19   2   2
1  17   3  17
2   4  15  16
3  12   1  18

In [ ]:
row_wise_sum=data.sum(axis=1) # row wise sum
col_sum=data.sum(axis=0) # col wise sum.

In [25]:
print(data)
print("row wise sum\n",row_wise_sum)
print("col wise sum\n",col_sum)

    A   B   C
0  19   2   2
1  17   3  17
2   4  15  16
3  12   1  18
row wise sum
 0    23
1    37
2    35
3    31
dtype: int64
col wise sum
 A    52
B    21
C    53
dtype: int64

In [95]:
data=pd.DataFrame(np.random.randint(1,10,size=(5,3)),columns=['A','B','C'])

In [96]:
data.replace(data.at[0,'A'],np.nan,inplace=True) # this replaces the value present at this location and also duplicated of this values in entire dataframe.

In [97]:
data

     A    B    C
0  NaN  2.0  8.0
1  7.0  7.0  1.0
2  5.0  8.0  NaN
3  6.0  NaN  2.0
4  4.0  4.0  7.0

In [98]:
data.isnull().sum()

A    1
B    1
C    1
dtype: int64

In [99]:
data=data.fillna(data.mean())

In [100]:
data

     A     B    C
0  5.5  2.00  8.0
1  7.0  7.00  1.0
2  5.0  8.00  4.5
3  6.0  5.25  2.0
4  4.0  4.00  7.0

In [30]:
import pandas as pd
import numpy as np
data=pd.DataFrame(np.random.randint(1,20,size=(6,4)))

In [31]:
data.iloc[0,1]=np.nan # this iloc can be used for easy accessing
data.iloc[4,3]=np.nan 
data.iloc[2,2]=np.nan

In [32]:
data

    0     1     2     3
0   7   NaN  13.0   1.0
1  15  17.0  16.0   4.0
2   4  14.0   NaN  15.0
3  18   2.0  11.0   8.0
4  19  17.0   2.0   NaN
5  12   1.0   1.0  19.0

In [35]:
data.dropna(inplace=True) # this wil only drop the nan containing rows and columns

In [36]:
data

    0     1     2     3
1  15  17.0  16.0   4.0
3  18   2.0  11.0   8.0
5  12   1.0   1.0  19.0

In [ ]:
data=pd.DataFrame({'category':np.random.choice(['A','B','C'],size=10),'Values':np.random.randint(1,100,size=10)}) # choice is used to fill the element of the column on your choice. size =10 are the rows only as we giving colums by selfs

In [51]:
data

  category  Values
0        B      68
1        B      25
2        B      79
3        C      56
4        B       9
5        A      88
6        C      61
7        C      19
8        C      20
9        A      52

In [52]:
data.groupby('category')['Values'].agg(['sum','mean'])

          sum   mean
category
A         140  70.00
B         181  45.25
C         156  39.00

In [10]:
data1=pd.DataFrame({'key':np.random.choice(['A','B']),'value1':np.random.randint(1,20,size=10)})
data2=pd.DataFrame({'key':np.random.choice(['A','B']),'value2':np.random.randint(20,40,size=10)})

In [63]:
data=data1.merge(data2,on='key')

In [64]:
data

   key  value1  value2
0    A       6      32
1    A       6      27
2    A       6      36
3    A       6      36
4    A       6      28
..  ..     ...     ...
95   A      19      34
96   A      19      22
97   A      19      23
98   A      19      22
99   A      19      21

[100 rows x 3 columns]

In [59]:
import pandas as pd
import numpy as np
data1=pd.DataFrame({'key1':np.random.choice(['A','B'],size=5),'value1':np.random.randint(1,20,size=5)})
data2=pd.DataFrame({'key2':np.random.choice(['C','D'],size=5),'value2':np.random.randint(20,40,size=5)})

In [60]:
data_row=pd.concat([data1,data2],axis=0)# along rows
data_col=pd.concat([data1,data2],axis=1) # along cols

In [61]:
print("first dataframe:\n",data1)
print("second dataframe:\n",data2)

first dataframe:
   key1  value1
0    B      19
1    A       3
2    B       7
3    B       4
4    B      15
second dataframe:
   key2  value2
0    C      27
1    C      25
2    D      29
3    C      35
4    D      33

In [46]:
print("row wise:\n",data_row)
print("col wise:\n",data_col)

row wise:
   key1  value1 key2  value2
0    A      12    D      21
1    B       7    D      38
2    A       9    D      20
3    A      15    D      36
4    B      16    D      33
col wise:
   key1  value1 key2  value2
0    A    12.0  NaN     NaN
1    B     7.0  NaN     NaN
2    A     9.0  NaN     NaN
3    A    15.0  NaN     NaN
4    B    16.0  NaN     NaN
0  NaN     NaN    D    21.0
1  NaN     NaN    D    38.0
2  NaN     NaN    D    20.0
3  NaN     NaN    D    36.0
4  NaN     NaN    D    33.0

In [88]:
import pandas as pd
import numpy as np
from datetime import datetime
date_range=pd.date_range(start='1-1-2022',end='31-12-2022')
data=pd.DataFrame(date_range,columns=['date'])
data['data']=(np.random.randint(1,20,size=(len(date_range))))
data.set_index('date',inplace=True)

In [89]:
data

            data
date
2022-01-01    12
2022-01-02     6
2022-01-03     1
2022-01-04     6
2022-01-05     7
...          ...
2022-12-27    13
2022-12-28    10
2022-12-29     7
2022-12-30     7
2022-12-31     2

[365 rows x 1 columns]

In [91]:
#resample('M'): group data by month (assumes DateTimeIndex).
#.mean(): take average for each month.

df=data.resample('M').mean()
df

C:\Users\NINJA-C7\AppData\Local\Temp\ipykernel_6236\551868389.py:4: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df=data.resample('M').mean()

                 data
date
2022-01-31   9.709677
2022-02-28   9.285714
2022-03-31  10.806452
2022-04-30  10.866667
2022-05-31   9.322581
2022-06-30  10.066667
2022-07-31   9.774194
2022-08-31  10.580645
2022-09-30   8.066667
2022-10-31   8.161290
2022-11-30  10.133333
2022-12-31  10.612903

In [ ]:
import pandas as pd
import numpy as np
# we need to make a dataframe with multiindex
index=pd.MultiIndex.from_arrays([np.array(['A','B','C']),np.array(['one','two','three'])],names=['category','subcategory']) # index olumns are not counted.
data=pd.DataFrame(np.random.randint(1,20,size=(3,2)),index=index,columns=['value1','value2'])

In [12]:
data

                      value1  value2
category subcategory
A        one              10      13
B        two               8       9
C        three            16      16

In [33]:
print(data.loc['A']) #iloc uses integer position not strings or characters
# indexing at index 'A'
print(data.loc['B','two'])

             value1  value2
subcategory
one              10      13
value1    8
value2    9
Name: (B, two), dtype: int32

In [ ]:
# calculating the sum of each category and sub category.
data.groupby('category')[['value1','value2']].agg(['sum'])

         value1 value2
            sum    sum
category
A            10     13
B             8      9
C            16     16

In [49]:
data.groupby('subcategory')[['value1','value2']].sum()

             value1  value2
subcategory
one              10      13
three            16      16
two               8       9

In [70]:
from datetime import datetime
date=pd.date_range(start='1-1-2025',end='3-1-2025')
data=pd.DataFrame({'category':np.random.choice(['A','B','C'],size=10),'Date':np.random.choice(date,size=10),'Value':np.random.randint(1,40,size=10)})

In [71]:
data

  category       Date  Value
0        B 2025-02-03     14
1        A 2025-01-09     39
2        A 2025-01-07     36
3        C 2025-02-16     22
4        A 2025-01-23     35
5        B 2025-02-19     16
6        A 2025-02-24     25
7        A 2025-02-11     22
8        C 2025-02-24      7
9        A 2025-01-26     32

In [75]:
#data.groupby(['category','Date'])['Value'].sum()
pivot=data.pivot_table(values='Value',index='Date',columns='category',aggfunc='sum')

In [76]:
pivot

category       A     B     C
Date
2025-01-07  36.0   NaN   NaN
2025-01-09  39.0   NaN   NaN
2025-01-23  35.0   NaN   NaN
2025-01-26  32.0   NaN   NaN
2025-02-03   NaN  14.0   NaN
2025-02-11  22.0   NaN   NaN
2025-02-16   NaN   NaN  22.0
2025-02-19   NaN  16.0   NaN
2025-02-24  25.0   NaN   7.0